version: 2 # https://circleci.com/docs/2.0/language-javascript/
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers # https://hub.docker.com/r/circleci/node/

    steps:
      - checkout

      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}

      - run: npm run lint

      - run: npm test:report

      - store_artifacts:
          path: test-results.xml

      - store_artifacts:
          path: tests/visual/screenshots

      - store_test_results:
          path: test-results.xml
